model:
  internvl_path: /data/phd/jinjiachun/ckpt/OpenGVLab/InternVL3_5-1B
  high_dim: 4096
  down_dim: 16
  diffhead:
    x_dim: 16
    hidden_size: 512
    z_dim: 1024
    depth: 16
  train_llm: true
# --------------------------------------------------
train:
  root: /data/phd/jinjiachun/experiment
  resume_path: /data/phd/jinjiachun/experiment/down_proj/0917_joint_training_llm_off/internvl-down_proj-36000
  global_step: 36000

  exp_name: &exp_name down_proj
  proj_name: *exp_name
  output_dir: 0917_joint_training_llm_on
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: swanlab

  lr: 1e-4
  num_iter: 500000
  save_every: 2000

  hp_loss_gen: 10.0
  hp_loss_und: 1.0
  hp_loss_und_ori: 1.0

data:
  batch_size: &batch_size 30
  gen:
    wds_path: [/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB]
    img_size: 448
    cfg_drop_rate: 0.1
    num_img_token: 256
    max_seq_length: 512
    buffer_size: 10000
    batch_size: *batch_size
    num_workers: 8
  und:
    batch_size: 8
    num_workers: 1
    max_seq_length: 512