ann: 用理解蒸馏训一个clip down projector出来，连着internvl的lm backbone一起训
model:
  internvl_path: /data/phd/jinjiachun/ckpt/OpenGVLab/InternVL3_5-1B
  proj_type: linear #[linear, transformer]
  high_dim: 4096
  down_dim: 16
  # below used only for transformer
  hidden_size: 512
  num_tokens: 256
  num_heads: 16
  depth: 16
  tune_llm: false
# --------------------------------------------------
train:
  root: /data/phd/jinjiachun/experiment
  resume_path: null
  global_step: 0

  exp_name: &exp_name down_proj
  wandb_proj: *exp_name
  output_dir: 0916_llava_distill_linear_debug
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: null

  lr: 1e-4
  num_iter: 500000
  save_every: 2000

data:
  batch_size: 2
  num_workers: 2