model:
  vae_path: /data/phd/jinjiachun/ckpt/stabilityai/stable-diffusion-3.5-medium/vae
  internvl_path: /data/phd/jinjiachun/ckpt/OpenGVLab/InternVL3_5-8B
  mmdit:
    sd3_5_path: /data/phd/jinjiachun/ckpt/stabilityai/stable-diffusion-3.5-medium
    lfq_vit:
      hidden_size: 1024
      depth: 16
      num_heads: 16
      grid_size: 16
      input_dim: 4096
      output_dim: 16
    load_pretrained: true

train:
  root: /data/phd/jinjiachun/experiment
  resume_path:
  skip_keys: []
  global_step: 0

  exp_name: &exp_name vq_decoder
  proj_name: *exp_name
  output_dir: 0926_lfq_sd3_decoder
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: null

  lr: 1e-4
  num_iter: 100000
  save_every: 2000

  hp_loss_gen: 1.0

data:
  wds_path: [/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB]
  img_size: 448
  cfg_drop_rate: 0.1
  num_img_token: 256
  max_seq_length: 512
  buffer_size: 50
  batch_size: 24
  num_workers: 8
